// Minimal app-shell cache so the PWA opens instantly and installs cleanly.
// Never intercepts the GitHub API or the MediaPipe CDN — those must always hit the network.
const CACHE_NAME = "bpb-shell-v205";
const SHELL_FILES = [
  "./",
  "./index.html",
  "./style.css?v=161",
  "./app.js?v=178",
  "./wheel-mode.js?v=4",
  "./modes/squat.js",
  "./modes/situp.js",
  "./share-messages.js?v=136",
  "./api.js",
  "./storage.js",
  "./territory-location.js",
  "./roadtrip.js",
  "./sync.js",
  "./rep-counter.js",
  "./camera.js",
  "./stats.js",
  "./screens/summary.js",
  "./screens/dashboard.js",
  "./screens/mode-stats.js?v=133",
  "./screens/comparison.js?v=132",
  "./screens/session-detail.js?v=3",
  "./screens/challenges.js",
  "./screens/settings.js",
  "./screens/explore-modes.js?v=140",
  "./screens/modifiers.js?v=100",
  "./screens/users.js",
  "./workout-modes.js?v=150",
  "./horse.js",
  "./horse-words.js",
  "./screens/horse.js",
  "./poker.js",
  "./chase.js",
  "./ladder-rivals.js",
  "./voice.js?v=148",
  "./voice-lines.js?v=137",
  "./manifest.json",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/apple-touch-icon.png",
  "./assets/mascot.jpg",
  "./assets/pyramid/stone-tile.png",
];

// Cached if present, but a miss must not fail the install — the voice clips are
// generated by scripts/generate-voice.js and may not exist in a fresh checkout.
// The ~200 individual clips are deliberately not precached (too heavy for
// install); they land in this same cache via the fetch handler on first use.
const OPTIONAL_FILES = [
  "./assets/voice/manifest.json",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(SHELL_FILES).then(() =>
        Promise.all(OPTIONAL_FILES.map((f) => cache.add(f).catch(() => {})))
      )
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return; // let GitHub API / CDN requests pass through
  if (event.request.method !== "GET") return;
  if (url.pathname.endsWith("/challenges.json")) return; // always fetch fresh — never cache-first

  if (event.request.mode === "navigate") {
    event.respondWith(networkFirstNavigation(event.request));
    return;
  }

  const network = fetchAndCache(event.request);
  event.waitUntil(network.then(() => {}).catch(() => {}));
  event.respondWith(staleWhileRevalidate(event.request, network));
});

async function cacheSuccessfulResponse(request, response) {
  // Cache persistence is an optimization, never a reason to discard a valid
  // network response. Cache Storage can reject partial media responses (206)
  // or writes when device quota is tight.
  if (!response || response.status !== 200) return;
  try {
    const cache = await caches.open(CACHE_NAME);
    await cache.put(request, response.clone());
  } catch (e) {
    // Continue serving the network response; a later request can retry.
  }
}

async function networkFirstNavigation(request) {
  try {
    const response = await fetch(request);
    await cacheSuccessfulResponse(request, response);
    return response;
  } catch (e) {
    return (await caches.match(request)) || (await caches.match("./index.html"));
  }
}

async function fetchAndCache(request) {
  const response = await fetch(request);
  await cacheSuccessfulResponse(request, response);
  return response;
}

async function staleWhileRevalidate(request, network) {
  const cached = await caches.match(request);
  if (cached) return cached;
  try {
    return await network;
  } catch (e) {
    return Response.error();
  }
}
